server:
  port: 8005
service-url:
  feign-business1-server: http://localhost:8003
spring:
  application:
    name: gateway
  cloud:
    gateway:
      # 1.普通路由功能
      routes:
        - id: path_route #路由的ID
          uri: ${service-url.feign-business1-server}/user/create #匹配后路由地址
          predicates: # 断言，路径相匹配的进行路由
            - Path=/user/create
      # 2.注册中心寻找服务功能
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:123456@localhost:8001/eureka/