server:
  port: 8004
spring:
  application:
    name: feign-business2-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:123456@localhost:8001/eureka/

feign:
  hystrix:
    enabled: true #在Feign中开启Hystrix